services:
  - type: web
    name: kalchakra-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn kalchakra_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kalchakra_project.settings
      - key: PYTHON_VERSION
        value: 3.11
